"""
Django settings for origin project.

Generated by 'django-admin startproject' using Django 1.8.3.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'j^%32111th*jd#&h&=z__i6x+h(@2d2_c&ie^^k*7xyp#@&96$'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []   #is not applied while debug mode is on or when running tests.
#Once you are going to move your site to production and set DEBUG to False, you
#will have to add your domain/host to this setting in order to allow it to serve the Django site.


# Application definition

INSTALLED_APPS = (
    'django.contrib.admin',#this is an administration site
    'django.contrib.auth',#this is an authentication framework
    'django.contrib.contenttypes',#this is a framework for content types
    'django.contrib.sessions',#this is a session framework
    'django.contrib.messages',#this is a messaging framework
    'django.contrib.staticfiles', #this is a framework for managing static files
    'contact',
    'subscription',
    'database',
    'polls',
    'blog',
    'taggit',
    #'disqus',
    #'bootstrap3',
    #'CpMap',
    #'threadedcomments',
    #'django_comments',
    'django.contrib.sites',
    'django.contrib.sitemaps',
    'haystack',
)

SITE_ID=3

# Define the search engine backends for haystack
HAYSTACK_CONNECTIONS={
    'default':{
        'ENGINE':'haystack.backends.solr_backend.SolrEngine',
        'URL':'http://127.0.0.1:8983/solr/blog'
        },
}





#MIDDLEWARE_CLASSES is a tuple containing middlewares to be executed.

MIDDLEWARE_CLASSES = (
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
)

ROOT_URLCONF = 'origin.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR,'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'origin.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases


DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'ddk5c3r8jv6eao',
        'USER':'wtzvndsrnapvjl',
        'PASSWORD':'83n2AdqUEEAGjBmhIHQ8-Cfh0X',
        'HOST':'ec2-107-21-221-107.compute-1.amazonaws.com',
        'PORT':'5432',
    }
}

# Giving the email parameters for default mail
EMAIL_HOST='smtp.126.com'
EMAIL_HOST_USER='extremeways@126.com'
EMAIL_HOST_PASSWORD='II68738050'
EMAIL_PORT=25
EMAIL_USE_TLS=True


# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS=(
   os.path.join(BASE_DIR, "static"),
                  )
STATICFILES_STORAGE='whitenoise.django.GzipManifestStaticFilesStorage'
STATIC_ROOT='staticfiles'

